package com.model;

public class Customer {
   private int customerId; // generated by database
   private String customerUsername;
   private String customerPassword;
   private String customerName;
   private String customerEmail;

   public Customer() {
       this.customerUsername = null;
       this.customerPassword = null;
       this.customerName = null;
       this.customerEmail = null;
   }

    public Customer(String customerUsername, String customerPassword, String customerName, String customerEmail) {
        this.customerUsername = customerUsername;
        this.customerPassword = customerPassword;
        this.customerName = customerName;
        this.customerEmail = customerEmail;
    }

    public Customer(Customer customer) {
       this.customerId = customer.customerId;
        this.customerUsername = customer.customerUsername;
        this.customerPassword = customer.customerPassword;
        this.customerName = customer.customerName;
        this.customerEmail = customer.customerEmail;
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public String getCustomerUsername() {
        return customerUsername;
    }

    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }

    public String getCustomerPassword() {
        return customerPassword;
    }

    public void setCustomerPassword(String customerPassword) {
        this.customerPassword = customerPassword;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
}
