package com.model;

public class Menu {
    private int item_id; // generated by database
    private String item_name;
    private String item_price;
    private String item_description;
    private String item_pic;

    public Menu() {

    }

    public Menu(String item_name, String item_price, String item_description, String item_pic) {
        this.item_name = item_name;
        this.item_price = item_price;
        this.item_description = item_description;
        this.item_pic = item_pic;
    }

    public Menu(Menu menu) {
        this.item_name = menu.item_name;
        this.item_price = menu.item_price;
        this.item_description = menu.item_description;
        this.item_pic = menu.item_pic;
    }

    public int getItem_id() {
        return item_id;
    }

    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }

    public String getItem_name() {
        return item_name;
    }

    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    public String getItem_price() {
        return item_price;
    }

    public void setItem_price(String item_price) {
        this.item_price = item_price;
    }

    public String getItem_description() {
        return item_description;
    }

    public void setItem_description(String item_description) {
        this.item_description = item_description;
    }

    public String getItem_pic() {
        return item_pic;
    }

    public void setItem_pic(String item_pic) {
        this.item_pic = item_pic;
    }
}
