package com.model;

public class Menu {
    private int itemId; // generated by database
    private String itemName;
    private double itemPrice;
    private String itemDescription;
    private String itemPic; // url to picture

    public Menu() {
        this.itemName = null;
        this.itemPrice = 0;
        this.itemDescription = null;
        this.itemPic = null;
    }

    public Menu(String itemName, double itemPrice, String itemDescription, String itemPic) {
        this.itemName = itemName;
        this.itemPrice = itemPrice;
        this.itemDescription = itemDescription;
        this.itemPic = itemPic;
    }

    public Menu(Menu menu) {
        this.itemId = menu.itemId;
        this.itemName = menu.itemName;
        this.itemPrice = menu.itemPrice;
        this.itemDescription = menu.itemDescription;
        this.itemPic = menu.itemPic;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public double getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(double itemPrice) {
        this.itemPrice = itemPrice;
    }

    public String getItemDescription() {
        return itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public String getItemPic() {
        return itemPic;
    }

    public void setItemPic(String itemPic) {
        this.itemPic = itemPic;
    }
}
