package com.model;

import java.util.Date;

public class Order {
    private int orderId; // generated by database
    private String orderStatus;
    private Date orderDate;
    private double orderTotalPrice;
    private int orderQuantity;
    private int itemId;
    private int customerId;

    public Order() {
        this.orderStatus = null;
        this.orderDate = null;
        this.orderTotalPrice = 0;
        this.orderQuantity = 0;
        this.itemId = 0;
        this.customerId = 0;
    }

    public Order(String orderStatus, Date orderDate, double orderTotalPrice, int orderQuantity, int itemId, int customerId) {
        this.orderStatus = orderStatus;
        this.orderDate = orderDate;
        this.orderTotalPrice = orderTotalPrice;
        this.orderQuantity = orderQuantity;
        this.itemId = itemId;
        this.customerId = customerId;
    }

    public Order(Order order) {
        this.orderId = order.orderId;
        this.orderStatus = order.orderStatus;
        this.orderDate = order.orderDate;
        this.orderTotalPrice = order.orderTotalPrice;
        this.orderQuantity = order.orderQuantity;
        this.itemId = order.itemId;
        this.customerId = order.customerId;
    }

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public double getOrderTotalPrice() {
        return orderTotalPrice;
    }

    public void setOrderTotalPrice(double orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }

    public int getOrderQuantity() {
        return orderQuantity;
    }

    public void setOrderQuantity(int orderQuantity) {
        this.orderQuantity = orderQuantity;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
}
