package com.model;

import java.util.Date;

public class Sales {
    private int salesId; // generated by database
    private Date salesDate;
    private int orderId;
    private int paymentId;

    public Sales() {
        this.salesDate = null;
        this.orderId = 0;
        this.paymentId = 0;
    }

    public Sales(Date salesDate, int orderId, int paymentId) {
        this.salesDate = salesDate;
        this.orderId = orderId;
        this.paymentId = paymentId;
    }

    public Sales(Sales sales) {
        this.salesId = sales.salesId;
        this.salesDate = sales.salesDate;
        this.orderId = sales.orderId;
        this.paymentId = sales.paymentId;
    }

    public int getSalesId() {
        return salesId;
    }

    public void setSalesId(int salesId) {
        this.salesId = salesId;
    }

    public Date getSalesDate() {
        return salesDate;
    }

    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }
}
