package com.model;

public class Worker {
    private int workerId; // generated by database
    private String workerUsername;
    private String workerPassword;
    private String workerName;
    private String workerEmail;
    private String managerId;

    public Worker() {
        this.workerUsername = null;
        this.workerPassword = null;
        this.workerName = null;
        this.workerEmail = null;
        this.managerId = null;
    }

    public Worker(String workerUsername, String workerPassword, String workerName, String workerEmail, String managerId) {
        this.workerUsername = workerUsername;
        this.workerPassword = workerPassword;
        this.workerName = workerName;
        this.workerEmail = workerEmail;
        this.managerId = managerId;
    }

    public Worker(Worker worker) {
        this.workerId = worker.workerId;
        this.workerUsername = worker.workerUsername;
        this.workerPassword = worker.workerPassword;
        this.workerName = worker.workerName;
        this.workerEmail = worker.workerEmail;
        this.managerId = worker.managerId;
    }

    public int getWorkerId() {
        return workerId;
    }

    public void setWorkerId(int workerId) {
        this.workerId = workerId;
    }

    public String getWorkerUsername() {
        return workerUsername;
    }

    public void setWorkerUsername(String workerUsername) {
        this.workerUsername = workerUsername;
    }

    public String getWorkerPassword() {
        return workerPassword;
    }

    public void setWorkerPassword(String workerPassword) {
        this.workerPassword = workerPassword;
    }

    public String getWorkerName() {
        return workerName;
    }

    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }

    public String getWorkerEmail() { return workerEmail; }

    public void setWorkerEmail(String workerEmail) { this.workerEmail = workerEmail; }

    public String getManagerId() {
        return managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
}
