package com.model;

public class Worker {
    private int worker_id; // generated by database
    private String username;
    private String password;
    private String worker_name;
    private String worker_email;
    private Worker manager;

    public Worker() {
        this.username = null;
        this.password = null;
        this.worker_name = null;
        this.worker_email = null;
        this.manager = null;
    }

    public Worker(String username, String password, String worker_name, String worker_email, Worker manager) {
        this.username = username;
        this.password = password;
        this.worker_name = worker_name;
        this.worker_email = worker_email;
        this.manager = manager;
    }

    public Worker(Worker worker) {
        this.username = worker.username;
        this.password = worker.password;
        this.worker_name = worker.worker_name;
        this.worker_email = worker.worker_email;
        this.manager = worker.manager;
    }

    public int getWorker_id() {
        return worker_id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getWorker_name() {
        return worker_name;
    }

    public String getWorker_email() {
        return worker_email;
    }

    public Worker getManager() {
        return manager;
    }

    public void setWorker_id(int worker_id) {
        this.worker_id = worker_id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setWorker_name(String worker_name) {
        this.worker_name = worker_name;
    }

    public void setWorker_email(String worker_email) {
        this.worker_email = worker_email;
    }

    public void setManager(Worker manager) {
        this.manager = manager;
    }
}
